on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "app/*"
      - "config/*"
      - "Dockerfile"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      REGISTRY_BASE: asia-northeast1-docker.pkg.dev
      REGION: asia-northeast1
      REPOSITORY: pleroma
      SERVICE: app
    permissions:
      contents: "read"
      id-token: "write"
    
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: google-github-actions/auth@v2
        id: auth
        with:
          token_format: "access_token"
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ env.REGISTRY_BASE }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          buld-args: MIX_ENV=prod
          tags: "${{ env.REGISTRY_BASE }}/${{ secrets.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: pleroma
          region: ${{ env.REGION }}
          image: "${{ env.REGISTRY_BASE }}/${{ secrets.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
